apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
  namespace: cert-manager
spec:
  isCA: true
  commonName: Kubernetes Ingress
  secretName: ingress-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 4320h
  subject:
    organizations:
      - cluster
    organizationalUnits:
      - Kubernetes
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io