apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultlan-wildcard
  namespace: cert-manager
spec:
  secretName: vaultlan-tls
  commonName: "*.vaultlan.com"
  dnsNames:
    - "vaultlan.com"
    - "*.vaultlan.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
