resources:
  - grafana-ingress.yaml
  - alertmanager-ingress.yaml
  - prometheus-ingress.yaml

helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    version: 72.5.2
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    valuesFile: values.yaml

configMapGenerator:
  - name: demo-dashboard
    namespace: monitoring
    files:
      - otel-grafana-dashboards/demo-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"

  - name: exemplars-dashboard
    namespace: monitoring
    files:
      - otel-grafana-dashboards/exemplars-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"

  - name: otel-collector-dashboard
    namespace: monitoring
    files:
      - otel-grafana-dashboards/opentelemetry-collector.json
    options:
      labels:
        grafana_dashboard: "1"

  - name: spanmetrics-dashboard
    namespace: monitoring
    files:
      - otel-grafana-dashboards/spanmetrics-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
  annotations: {}