resources:
  - otel-collector-rbac.yaml

helmCharts:
  - name: opentelemetry-collector
    releaseName: otel-collector
    version: 0.120.0
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    namespace: monitoring
    valuesFile: values.yaml