persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi

tempo:
  search:
    enabled: true
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

  metricsGenerator:
    enabled: true