cluster:
  inlineManifests:
    - name: prometheus-crds-install
      contents: |
        ---
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: prometheus-crds-install
          namespace: kube-system
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: prometheus-crds-install
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            name: prometheus-crds-install
            namespace: kube-system
        ---
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: prometheus-crds-install
          namespace: kube-system
        spec:
          backoffLimit: 10
          template:
            spec:
              serviceAccountName: prometheus-crds-install
              restartPolicy: OnFailure
              containers:
                - name: kubectl
                  image: bitnami/kubectl:latest
                  command:
                    - /bin/sh
                    - -c
                    - |
                      echo "Installing Prometheus CRDs..."
                      kubectl apply -f https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.82.1/stripped-down-crds.yaml